### PR TITLE
Add rudimentary support for fat MachO files

### PR DESCRIPTION
**Pull request by Keno**
@staticfloat

### CODE REVIEW

**Comment by staticfloat** [comment]
So while I do want to support Fat MachO files as transparently as possible, I think what we need to do is rework how `readmeta` works, because I don't think we can sanely support both the `readmeta()` API we have right now (e.g. "give me an IO and I'll give you an object file") while supporting Fat MachO files.  We need to have a "collection"-type interface, where `readmeta` is allowed to yield multiple object files, because right now a `FatMachOHandle` can't participate in most of the rest of the API here.  I can't get the headers, sections, symbols, etc... within a `FatMachOHandle`, because it doesn't play by the rules of the rest of the API; I have to first iterate over it.

So I guess what I'm saying is, I want to be able to program generically enough that we can use `test_libfoo_and_fooifier()` on both a `.so` and a `.dylib` and not worry about it.  Perhaps all this blathering can be resolved by just having `readmeta()` return an `ObjectHandle[]` and it returns one for all `.so` and `.dll` files, but might return more for a `.dylib` file.  That of course pushes some complexity up onto things like `BinaryBuilder`, since if we're looking for symbols, it's then necessary to determine which architecture we're suppose to pay attention to.

**Comment by Keno** [comment]
How about if `FatMachOHandle` implicitly behaved as the first object it contained, since Symbols, etc will generally be equal between fat objects and code that wants to be aware of it can deal with it explicitly.

**Comment by staticfloat** [comment]
I don't think that's a good idea since the first is usually the 32-bit, and that's usually not what we want.  I also think we are in the wrong field to expect things like symbols to be the same across 32-bit and 64-bit, unfortunately.

I don't have time to fix this right now unfortunately, but I will add this to the back of my burner right now.  In the meantime, feel free to merge this so you can continue to get work done, but I don't want to make a tagged release until we have something that is satisfactory.

**Comment by maleadt** [comment]
Rebased at https://github.com/maleadt/ObjectFile.jl/tree/fatmacho.

@staticfloat Any recent thoughts on what the interface for universal binaries would look like? I'd like to use ObjectFile.jl to parse generated binaries in Metal.jl.

**Pull request closed without merging**
